# Generated by Django 3.0.5 on 2020-07-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdata',
            name='character',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerdata',
            name='imgSrc',
            field=models.URLField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='level',
            field=models.CharField(max_length=200),
        ),
    ]
