# Generated by Django 3.0.5 on 2020-07-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0002_auto_20200723_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdata',
            name='imgSrc',
            field=models.CharField(max_length=200),
        ),
    ]
