# Generated by Django 3.0.5 on 2020-07-29 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0005_playerdata_mrfloor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='playerdata',
            name='Party',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='parsed_data.Party'),
            preserve_default=False,
        ),
    ]
