# Generated by Django 3.0.5 on 2020-07-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0006_auto_20200729_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerdata',
            old_name='Party',
            new_name='party',
        ),
    ]
