# Generated by Django 3.0.5 on 2020-07-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0007_auto_20200729_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerdata',
            name='party',
        ),
    ]
