# Generated by Django 3.0.5 on 2020-07-29 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0008_remove_playerdata_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdata',
            name='party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parsed_data.Party'),
            preserve_default=False,
        ),
    ]
